### ISSUE TITLE
octo-sts

### ISSUE THREAD

**Issue by thepwagner** [helaili/github-oidc-auth-app#26]
Have you seen https://github.com/octo-sts/app/ ?

The number of people that have independently invented this solution is pretty surprising:

* Apr 2022 - https://github.com/github/actions-oidc-gateway-example (first time I'd seen this!)
* Jul 2022 - https://github.com/thepwagner/github-token-factory-oidc
* Apr 2023 - https://github.com/helaili/github-oidc-auth-app
* Jan 2024 - https://github.com/octo-sts/app

I'm sure there are more!

Sharing as you might find inspiration in any of these projects.
I'm not affiliated with Chainguard,  I abandoned my invention of this wheel when OctoSTS went open source: https://www.chainguard.dev/unchained/open-sourcing-octo-sts

**Comment by helaili** [comment]
Thanks! 

I wasn't aware of your implementation but definitely saw the Chainguard one and you rightfully guessed that there are others 😄. I know one where they cleverly check the PR that modifies the configuration file so that no one can provide access they don't personally own already 😉 @atkinchris

**Comment by atkinchris** [comment]
Nice to see `octo-sts` went open source. I remember looking at this before we built our own, internal-only version with the specific feature set we needed.

For our version, we're very aware that the GitHub App is risk given it's superset of permissions. We onboard new repositories using PRs - which include a status check to limit privilege escalation. This uses the `repos.getCollaboratorPermissionLevel` API to check the permissions of the PR author against the repositories that they're either onboarding or editing - and rejects PRs which would grant permissions that the author does not have.
